apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hp-wad02-poi-map-app-dev
  annotations:
    argocd/app-name: hp-wad02-poi-map-app-dev
    backstage.io/kubernetes-id: hp-wad02-poi-map-app
    backstage.io/kubernetes-namespace: hp-wad02
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rosa916-rvhvd/hp-wad02-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.rosa916.9nln.p1.openshiftapps.com/dev-pipelines/ns/hp-wad02/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.rosa916.9nln.p1.openshiftapps.com/k8s/ns/hp-wad02/deployments/hp-wad02-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.rosa916.9nln.p1.openshiftapps.com/#https://github.com/rosa916-rvhvd/hp-wad02-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://hp-wad02-poi-map-app-hp-wad02.apps.rosa916.9nln.p1.openshiftapps.com
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/hpgrahsl"
  system: workshop-system-hp-wad02
  consumesApis:
    - gateway-api-hp-wad02
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-hp-wad02
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/hpgrahsl"
